### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by ElisabetRD** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-ElisabetRD#1]
[InfografiaLibrerias.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-ElisabetRD/files/14527888/InfografiaLibrerias.pdf)

**Comment by AricelCastro** [comment]
Mi equipo le da una calificación de 19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
